// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tensorflow/core/framework/allocation_description.proto

package framework

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AllocationDescription struct {
	// Total number of bytes requested
	RequestedBytes int64 `protobuf:"varint,1,opt,name=requested_bytes,json=requestedBytes,proto3" json:"requested_bytes,omitempty"`
	// Total number of bytes allocated if known
	AllocatedBytes int64 `protobuf:"varint,2,opt,name=allocated_bytes,json=allocatedBytes,proto3" json:"allocated_bytes,omitempty"`
	// Name of the allocator used
	AllocatorName string `protobuf:"bytes,3,opt,name=allocator_name,json=allocatorName,proto3" json:"allocator_name,omitempty"`
	// Identifier of the allocated buffer if known
	AllocationId int64 `protobuf:"varint,4,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	// Set if this tensor only has one remaining reference
	HasSingleReference bool `protobuf:"varint,5,opt,name=has_single_reference,json=hasSingleReference,proto3" json:"has_single_reference,omitempty"`
	// Address of the allocation.
	Ptr uint64 `protobuf:"varint,6,opt,name=ptr,proto3" json:"ptr,omitempty"`
}

func (m *AllocationDescription) Reset()      { *m = AllocationDescription{} }
func (*AllocationDescription) ProtoMessage() {}
func (*AllocationDescription) Descriptor() ([]byte, []int) {
	return fileDescriptorAllocationDescription, []int{0}
}

func (m *AllocationDescription) GetRequestedBytes() int64 {
	if m != nil {
		return m.RequestedBytes
	}
	return 0
}

func (m *AllocationDescription) GetAllocatedBytes() int64 {
	if m != nil {
		return m.AllocatedBytes
	}
	return 0
}

func (m *AllocationDescription) GetAllocatorName() string {
	if m != nil {
		return m.AllocatorName
	}
	return ""
}

func (m *AllocationDescription) GetAllocationId() int64 {
	if m != nil {
		return m.AllocationId
	}
	return 0
}

func (m *AllocationDescription) GetHasSingleReference() bool {
	if m != nil {
		return m.HasSingleReference
	}
	return false
}

func (m *AllocationDescription) GetPtr() uint64 {
	if m != nil {
		return m.Ptr
	}
	return 0
}

func init() {
	proto.RegisterType((*AllocationDescription)(nil), "tensorflow.AllocationDescription")
}
func (this *AllocationDescription) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AllocationDescription)
	if !ok {
		that2, ok := that.(AllocationDescription)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RequestedBytes != that1.RequestedBytes {
		return false
	}
	if this.AllocatedBytes != that1.AllocatedBytes {
		return false
	}
	if this.AllocatorName != that1.AllocatorName {
		return false
	}
	if this.AllocationId != that1.AllocationId {
		return false
	}
	if this.HasSingleReference != that1.HasSingleReference {
		return false
	}
	if this.Ptr != that1.Ptr {
		return false
	}
	return true
}
func (this *AllocationDescription) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&framework.AllocationDescription{")
	s = append(s, "RequestedBytes: "+fmt.Sprintf("%#v", this.RequestedBytes)+",\n")
	s = append(s, "AllocatedBytes: "+fmt.Sprintf("%#v", this.AllocatedBytes)+",\n")
	s = append(s, "AllocatorName: "+fmt.Sprintf("%#v", this.AllocatorName)+",\n")
	s = append(s, "AllocationId: "+fmt.Sprintf("%#v", this.AllocationId)+",\n")
	s = append(s, "HasSingleReference: "+fmt.Sprintf("%#v", this.HasSingleReference)+",\n")
	s = append(s, "Ptr: "+fmt.Sprintf("%#v", this.Ptr)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringAllocationDescription(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *AllocationDescription) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllocationDescription) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RequestedBytes != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintAllocationDescription(dAtA, i, uint64(m.RequestedBytes))
	}
	if m.AllocatedBytes != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintAllocationDescription(dAtA, i, uint64(m.AllocatedBytes))
	}
	if len(m.AllocatorName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAllocationDescription(dAtA, i, uint64(len(m.AllocatorName)))
		i += copy(dAtA[i:], m.AllocatorName)
	}
	if m.AllocationId != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintAllocationDescription(dAtA, i, uint64(m.AllocationId))
	}
	if m.HasSingleReference {
		dAtA[i] = 0x28
		i++
		if m.HasSingleReference {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Ptr != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintAllocationDescription(dAtA, i, uint64(m.Ptr))
	}
	return i, nil
}

func encodeVarintAllocationDescription(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *AllocationDescription) Size() (n int) {
	var l int
	_ = l
	if m.RequestedBytes != 0 {
		n += 1 + sovAllocationDescription(uint64(m.RequestedBytes))
	}
	if m.AllocatedBytes != 0 {
		n += 1 + sovAllocationDescription(uint64(m.AllocatedBytes))
	}
	l = len(m.AllocatorName)
	if l > 0 {
		n += 1 + l + sovAllocationDescription(uint64(l))
	}
	if m.AllocationId != 0 {
		n += 1 + sovAllocationDescription(uint64(m.AllocationId))
	}
	if m.HasSingleReference {
		n += 2
	}
	if m.Ptr != 0 {
		n += 1 + sovAllocationDescription(uint64(m.Ptr))
	}
	return n
}

func sovAllocationDescription(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozAllocationDescription(x uint64) (n int) {
	return sovAllocationDescription(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AllocationDescription) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AllocationDescription{`,
		`RequestedBytes:` + fmt.Sprintf("%v", this.RequestedBytes) + `,`,
		`AllocatedBytes:` + fmt.Sprintf("%v", this.AllocatedBytes) + `,`,
		`AllocatorName:` + fmt.Sprintf("%v", this.AllocatorName) + `,`,
		`AllocationId:` + fmt.Sprintf("%v", this.AllocationId) + `,`,
		`HasSingleReference:` + fmt.Sprintf("%v", this.HasSingleReference) + `,`,
		`Ptr:` + fmt.Sprintf("%v", this.Ptr) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAllocationDescription(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *AllocationDescription) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAllocationDescription
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllocationDescription: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllocationDescription: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedBytes", wireType)
			}
			m.RequestedBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocationDescription
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestedBytes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocatedBytes", wireType)
			}
			m.AllocatedBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocationDescription
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AllocatedBytes |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocatorName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocationDescription
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAllocationDescription
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllocatorName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocationId", wireType)
			}
			m.AllocationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocationDescription
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AllocationId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasSingleReference", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocationDescription
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasSingleReference = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ptr", wireType)
			}
			m.Ptr = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllocationDescription
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ptr |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAllocationDescription(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAllocationDescription
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAllocationDescription(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAllocationDescription
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAllocationDescription
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAllocationDescription
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthAllocationDescription
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowAllocationDescription
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipAllocationDescription(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthAllocationDescription = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAllocationDescription   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("tensorflow/core/framework/allocation_description.proto", fileDescriptorAllocationDescription)
}

var fileDescriptorAllocationDescription = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4b, 0xc3, 0x40,
	0x18, 0xc6, 0xf3, 0xda, 0x5a, 0xf4, 0xb0, 0x2a, 0x41, 0x21, 0x20, 0x1c, 0x41, 0x11, 0x33, 0x25,
	0x82, 0xe0, 0xe6, 0x60, 0x71, 0x71, 0x91, 0x12, 0x37, 0x97, 0x70, 0x4d, 0xde, 0xa6, 0xc1, 0x24,
	0x57, 0xef, 0xae, 0x14, 0x37, 0x3f, 0x82, 0xdf, 0x42, 0x3f, 0x8a, 0x63, 0x47, 0x47, 0x7b, 0x2e,
	0x8e, 0x1d, 0x75, 0x93, 0xa4, 0x36, 0x29, 0xd2, 0xed, 0xe5, 0xf7, 0xfe, 0xee, 0x0f, 0xcf, 0x43,
	0xce, 0x15, 0xe6, 0x92, 0x8b, 0x7e, 0xca, 0xc7, 0x5e, 0xc8, 0x05, 0x7a, 0x7d, 0xc1, 0x32, 0x1c,
	0x73, 0x71, 0xef, 0xb1, 0x34, 0xe5, 0x21, 0x53, 0x09, 0xcf, 0x83, 0x08, 0x65, 0x28, 0x92, 0x61,
	0x31, 0xbb, 0x43, 0xc1, 0x15, 0x37, 0x49, 0x7d, 0xee, 0xf0, 0x07, 0xc8, 0xfe, 0x65, 0x25, 0x5f,
	0xd5, 0xae, 0x79, 0x42, 0x76, 0x04, 0x3e, 0x8c, 0x50, 0x2a, 0x8c, 0x82, 0xde, 0xa3, 0x42, 0x69,
	0x81, 0x0d, 0x4e, 0xc3, 0xdf, 0xae, 0x70, 0xa7, 0xa0, 0x85, 0xf8, 0xf7, 0x5c, 0x25, 0xae, 0xcd,
	0xc5, 0x0a, 0xcf, 0xc5, 0x63, 0xb2, 0x20, 0x5c, 0x04, 0x39, 0xcb, 0xd0, 0x6a, 0xd8, 0xe0, 0x6c,
	0xfa, 0xed, 0x8a, 0xde, 0xb0, 0x0c, 0xcd, 0x23, 0xd2, 0x5e, 0xfa, 0x7e, 0x12, 0x59, 0xcd, 0xf2,
	0xb6, 0xad, 0x1a, 0x5e, 0x47, 0xe6, 0x29, 0xd9, 0x1b, 0x30, 0x19, 0xc8, 0x24, 0x8f, 0x53, 0x0c,
	0x04, 0xf6, 0x51, 0x60, 0x1e, 0xa2, 0xb5, 0x6e, 0x83, 0xb3, 0xe1, 0x9b, 0x03, 0x26, 0x6f, 0xcb,
	0x95, 0xbf, 0xd8, 0x98, 0xbb, 0xa4, 0x31, 0x54, 0xc2, 0x6a, 0xd9, 0xe0, 0x34, 0xfd, 0x62, 0xec,
	0xbc, 0xc0, 0x64, 0x4a, 0x8d, 0xf7, 0x29, 0x35, 0x66, 0x53, 0x0a, 0x4f, 0x9a, 0xc2, 0xab, 0xa6,
	0xf0, 0xa6, 0x29, 0x4c, 0x34, 0x85, 0x0f, 0x4d, 0xe1, 0x4b, 0x53, 0x63, 0xa6, 0x29, 0x3c, 0x7f,
	0x52, 0x83, 0x58, 0x5c, 0xc4, 0x6e, 0x1d, 0x9d, 0x5b, 0xa5, 0xdd, 0x39, 0x58, 0x99, 0x60, 0xb7,
	0x08, 0x5b, 0x76, 0xe1, 0xee, 0x22, 0x4e, 0xd4, 0x60, 0xd4, 0x73, 0x43, 0x9e, 0x79, 0x4b, 0x95,
	0xad, 0x1e, 0x63, 0xfe, 0xaf, 0xcb, 0x6f, 0x80, 0x5e, 0xab, 0x2c, 0xee, 0xec, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0xa8, 0x92, 0x54, 0xf2, 0x01, 0x00, 0x00,
}
