// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tensorflow/core/framework/graph_transfer_info.proto

package framework

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strconv "strconv"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GraphTransferInfo_Destination int32

const (
	NOP     GraphTransferInfo_Destination = 0
	HEXAGON GraphTransferInfo_Destination = 1
)

var GraphTransferInfo_Destination_name = map[int32]string{
	0: "NOP",
	1: "HEXAGON",
}
var GraphTransferInfo_Destination_value = map[string]int32{
	"NOP":     0,
	"HEXAGON": 1,
}

func (GraphTransferInfo_Destination) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{7, 0}
}

type GraphTransferNodeInput struct {
	NodeId     int32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OutputPort int32 `protobuf:"varint,2,opt,name=output_port,json=outputPort,proto3" json:"output_port,omitempty"`
}

func (m *GraphTransferNodeInput) Reset()      { *m = GraphTransferNodeInput{} }
func (*GraphTransferNodeInput) ProtoMessage() {}
func (*GraphTransferNodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{0}
}

func (m *GraphTransferNodeInput) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferNodeInput) GetOutputPort() int32 {
	if m != nil {
		return m.OutputPort
	}
	return 0
}

type GraphTransferNodeInfo struct {
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeId      int32  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TypeName    string `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	SocOpId     int32  `protobuf:"varint,4,opt,name=soc_op_id,json=socOpId,proto3" json:"soc_op_id,omitempty"`
	PaddingId   int32  `protobuf:"varint,5,opt,name=padding_id,json=paddingId,proto3" json:"padding_id,omitempty"`
	InputCount  int32  `protobuf:"varint,6,opt,name=input_count,json=inputCount,proto3" json:"input_count,omitempty"`
	OutputCount int32  `protobuf:"varint,7,opt,name=output_count,json=outputCount,proto3" json:"output_count,omitempty"`
}

func (m *GraphTransferNodeInfo) Reset()      { *m = GraphTransferNodeInfo{} }
func (*GraphTransferNodeInfo) ProtoMessage() {}
func (*GraphTransferNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{1}
}

func (m *GraphTransferNodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphTransferNodeInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferNodeInfo) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *GraphTransferNodeInfo) GetSocOpId() int32 {
	if m != nil {
		return m.SocOpId
	}
	return 0
}

func (m *GraphTransferNodeInfo) GetPaddingId() int32 {
	if m != nil {
		return m.PaddingId
	}
	return 0
}

func (m *GraphTransferNodeInfo) GetInputCount() int32 {
	if m != nil {
		return m.InputCount
	}
	return 0
}

func (m *GraphTransferNodeInfo) GetOutputCount() int32 {
	if m != nil {
		return m.OutputCount
	}
	return 0
}

type GraphTransferConstNodeInfo struct {
	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeId int32    `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Shape  []int64  `protobuf:"varint,3,rep,packed,name=shape" json:"shape,omitempty"`
	Data   []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Dtype  DataType `protobuf:"varint,5,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
}

func (m *GraphTransferConstNodeInfo) Reset()      { *m = GraphTransferConstNodeInfo{} }
func (*GraphTransferConstNodeInfo) ProtoMessage() {}
func (*GraphTransferConstNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{2}
}

func (m *GraphTransferConstNodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphTransferConstNodeInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferConstNodeInfo) GetShape() []int64 {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *GraphTransferConstNodeInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GraphTransferConstNodeInfo) GetDtype() DataType {
	if m != nil {
		return m.Dtype
	}
	return DT_INVALID
}

type GraphTransferNodeInputInfo struct {
	NodeId    int32                     `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeInput []*GraphTransferNodeInput `protobuf:"bytes,2,rep,name=node_input,json=nodeInput" json:"node_input,omitempty"`
}

func (m *GraphTransferNodeInputInfo) Reset()      { *m = GraphTransferNodeInputInfo{} }
func (*GraphTransferNodeInputInfo) ProtoMessage() {}
func (*GraphTransferNodeInputInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{3}
}

func (m *GraphTransferNodeInputInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferNodeInputInfo) GetNodeInput() []*GraphTransferNodeInput {
	if m != nil {
		return m.NodeInput
	}
	return nil
}

type GraphTransferNodeOutputInfo struct {
	NodeId      int32   `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MaxByteSize []int32 `protobuf:"varint,2,rep,packed,name=max_byte_size,json=maxByteSize" json:"max_byte_size,omitempty"`
}

func (m *GraphTransferNodeOutputInfo) Reset()      { *m = GraphTransferNodeOutputInfo{} }
func (*GraphTransferNodeOutputInfo) ProtoMessage() {}
func (*GraphTransferNodeOutputInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{4}
}

func (m *GraphTransferNodeOutputInfo) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *GraphTransferNodeOutputInfo) GetMaxByteSize() []int32 {
	if m != nil {
		return m.MaxByteSize
	}
	return nil
}

type GraphTransferGraphInputNodeInfo struct {
	Name  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape []int64  `protobuf:"varint,2,rep,packed,name=shape" json:"shape,omitempty"`
	Dtype DataType `protobuf:"varint,3,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
}

func (m *GraphTransferGraphInputNodeInfo) Reset()      { *m = GraphTransferGraphInputNodeInfo{} }
func (*GraphTransferGraphInputNodeInfo) ProtoMessage() {}
func (*GraphTransferGraphInputNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{5}
}

func (m *GraphTransferGraphInputNodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphTransferGraphInputNodeInfo) GetShape() []int64 {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *GraphTransferGraphInputNodeInfo) GetDtype() DataType {
	if m != nil {
		return m.Dtype
	}
	return DT_INVALID
}

type GraphTransferGraphOutputNodeInfo struct {
	Name  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape []int64  `protobuf:"varint,2,rep,packed,name=shape" json:"shape,omitempty"`
	Dtype DataType `protobuf:"varint,3,opt,name=dtype,proto3,enum=tensorflow.DataType" json:"dtype,omitempty"`
}

func (m *GraphTransferGraphOutputNodeInfo) Reset()      { *m = GraphTransferGraphOutputNodeInfo{} }
func (*GraphTransferGraphOutputNodeInfo) ProtoMessage() {}
func (*GraphTransferGraphOutputNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{6}
}

func (m *GraphTransferGraphOutputNodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GraphTransferGraphOutputNodeInfo) GetShape() []int64 {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *GraphTransferGraphOutputNodeInfo) GetDtype() DataType {
	if m != nil {
		return m.Dtype
	}
	return DT_INVALID
}

// Protocol buffer representing a handle to a tensorflow resource. Handles are
// not valid across executions, but can be serialized back and forth from within
// a single run.
type GraphTransferInfo struct {
	NodeInfo       []*GraphTransferNodeInfo       `protobuf:"bytes,1,rep,name=node_info,json=nodeInfo" json:"node_info,omitempty"`
	ConstNodeInfo  []*GraphTransferConstNodeInfo  `protobuf:"bytes,2,rep,name=const_node_info,json=constNodeInfo" json:"const_node_info,omitempty"`
	NodeInputInfo  []*GraphTransferNodeInputInfo  `protobuf:"bytes,3,rep,name=node_input_info,json=nodeInputInfo" json:"node_input_info,omitempty"`
	NodeOutputInfo []*GraphTransferNodeOutputInfo `protobuf:"bytes,4,rep,name=node_output_info,json=nodeOutputInfo" json:"node_output_info,omitempty"`
	// Input Node parameters of transferred graph
	GraphInputNodeInfo  []*GraphTransferGraphInputNodeInfo  `protobuf:"bytes,5,rep,name=graph_input_node_info,json=graphInputNodeInfo" json:"graph_input_node_info,omitempty"`
	GraphOutputNodeInfo []*GraphTransferGraphOutputNodeInfo `protobuf:"bytes,6,rep,name=graph_output_node_info,json=graphOutputNodeInfo" json:"graph_output_node_info,omitempty"`
	// Destination of graph transfer
	Destination GraphTransferInfo_Destination `protobuf:"varint,7,opt,name=destination,proto3,enum=tensorflow.GraphTransferInfo_Destination" json:"destination,omitempty"`
}

func (m *GraphTransferInfo) Reset()      { *m = GraphTransferInfo{} }
func (*GraphTransferInfo) ProtoMessage() {}
func (*GraphTransferInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorGraphTransferInfo, []int{7}
}

func (m *GraphTransferInfo) GetNodeInfo() []*GraphTransferNodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetConstNodeInfo() []*GraphTransferConstNodeInfo {
	if m != nil {
		return m.ConstNodeInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetNodeInputInfo() []*GraphTransferNodeInputInfo {
	if m != nil {
		return m.NodeInputInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetNodeOutputInfo() []*GraphTransferNodeOutputInfo {
	if m != nil {
		return m.NodeOutputInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetGraphInputNodeInfo() []*GraphTransferGraphInputNodeInfo {
	if m != nil {
		return m.GraphInputNodeInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetGraphOutputNodeInfo() []*GraphTransferGraphOutputNodeInfo {
	if m != nil {
		return m.GraphOutputNodeInfo
	}
	return nil
}

func (m *GraphTransferInfo) GetDestination() GraphTransferInfo_Destination {
	if m != nil {
		return m.Destination
	}
	return NOP
}

func init() {
	proto.RegisterType((*GraphTransferNodeInput)(nil), "tensorflow.GraphTransferNodeInput")
	proto.RegisterType((*GraphTransferNodeInfo)(nil), "tensorflow.GraphTransferNodeInfo")
	proto.RegisterType((*GraphTransferConstNodeInfo)(nil), "tensorflow.GraphTransferConstNodeInfo")
	proto.RegisterType((*GraphTransferNodeInputInfo)(nil), "tensorflow.GraphTransferNodeInputInfo")
	proto.RegisterType((*GraphTransferNodeOutputInfo)(nil), "tensorflow.GraphTransferNodeOutputInfo")
	proto.RegisterType((*GraphTransferGraphInputNodeInfo)(nil), "tensorflow.GraphTransferGraphInputNodeInfo")
	proto.RegisterType((*GraphTransferGraphOutputNodeInfo)(nil), "tensorflow.GraphTransferGraphOutputNodeInfo")
	proto.RegisterType((*GraphTransferInfo)(nil), "tensorflow.GraphTransferInfo")
	proto.RegisterEnum("tensorflow.GraphTransferInfo_Destination", GraphTransferInfo_Destination_name, GraphTransferInfo_Destination_value)
}
func (x GraphTransferInfo_Destination) String() string {
	s, ok := GraphTransferInfo_Destination_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *GraphTransferNodeInput) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphTransferNodeInput)
	if !ok {
		that2, ok := that.(GraphTransferNodeInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NodeId != that1.NodeId {
		return false
	}
	if this.OutputPort != that1.OutputPort {
		return false
	}
	return true
}
func (this *GraphTransferNodeInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphTransferNodeInfo)
	if !ok {
		that2, ok := that.(GraphTransferNodeInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.NodeId != that1.NodeId {
		return false
	}
	if this.TypeName != that1.TypeName {
		return false
	}
	if this.SocOpId != that1.SocOpId {
		return false
	}
	if this.PaddingId != that1.PaddingId {
		return false
	}
	if this.InputCount != that1.InputCount {
		return false
	}
	if this.OutputCount != that1.OutputCount {
		return false
	}
	return true
}
func (this *GraphTransferConstNodeInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphTransferConstNodeInfo)
	if !ok {
		that2, ok := that.(GraphTransferConstNodeInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.NodeId != that1.NodeId {
		return false
	}
	if len(this.Shape) != len(that1.Shape) {
		return false
	}
	for i := range this.Shape {
		if this.Shape[i] != that1.Shape[i] {
			return false
		}
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return false
	}
	if this.Dtype != that1.Dtype {
		return false
	}
	return true
}
func (this *GraphTransferNodeInputInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphTransferNodeInputInfo)
	if !ok {
		that2, ok := that.(GraphTransferNodeInputInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NodeId != that1.NodeId {
		return false
	}
	if len(this.NodeInput) != len(that1.NodeInput) {
		return false
	}
	for i := range this.NodeInput {
		if !this.NodeInput[i].Equal(that1.NodeInput[i]) {
			return false
		}
	}
	return true
}
func (this *GraphTransferNodeOutputInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphTransferNodeOutputInfo)
	if !ok {
		that2, ok := that.(GraphTransferNodeOutputInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NodeId != that1.NodeId {
		return false
	}
	if len(this.MaxByteSize) != len(that1.MaxByteSize) {
		return false
	}
	for i := range this.MaxByteSize {
		if this.MaxByteSize[i] != that1.MaxByteSize[i] {
			return false
		}
	}
	return true
}
func (this *GraphTransferGraphInputNodeInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphTransferGraphInputNodeInfo)
	if !ok {
		that2, ok := that.(GraphTransferGraphInputNodeInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if len(this.Shape) != len(that1.Shape) {
		return false
	}
	for i := range this.Shape {
		if this.Shape[i] != that1.Shape[i] {
			return false
		}
	}
	if this.Dtype != that1.Dtype {
		return false
	}
	return true
}
func (this *GraphTransferGraphOutputNodeInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphTransferGraphOutputNodeInfo)
	if !ok {
		that2, ok := that.(GraphTransferGraphOutputNodeInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if len(this.Shape) != len(that1.Shape) {
		return false
	}
	for i := range this.Shape {
		if this.Shape[i] != that1.Shape[i] {
			return false
		}
	}
	if this.Dtype != that1.Dtype {
		return false
	}
	return true
}
func (this *GraphTransferInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphTransferInfo)
	if !ok {
		that2, ok := that.(GraphTransferInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.NodeInfo) != len(that1.NodeInfo) {
		return false
	}
	for i := range this.NodeInfo {
		if !this.NodeInfo[i].Equal(that1.NodeInfo[i]) {
			return false
		}
	}
	if len(this.ConstNodeInfo) != len(that1.ConstNodeInfo) {
		return false
	}
	for i := range this.ConstNodeInfo {
		if !this.ConstNodeInfo[i].Equal(that1.ConstNodeInfo[i]) {
			return false
		}
	}
	if len(this.NodeInputInfo) != len(that1.NodeInputInfo) {
		return false
	}
	for i := range this.NodeInputInfo {
		if !this.NodeInputInfo[i].Equal(that1.NodeInputInfo[i]) {
			return false
		}
	}
	if len(this.NodeOutputInfo) != len(that1.NodeOutputInfo) {
		return false
	}
	for i := range this.NodeOutputInfo {
		if !this.NodeOutputInfo[i].Equal(that1.NodeOutputInfo[i]) {
			return false
		}
	}
	if len(this.GraphInputNodeInfo) != len(that1.GraphInputNodeInfo) {
		return false
	}
	for i := range this.GraphInputNodeInfo {
		if !this.GraphInputNodeInfo[i].Equal(that1.GraphInputNodeInfo[i]) {
			return false
		}
	}
	if len(this.GraphOutputNodeInfo) != len(that1.GraphOutputNodeInfo) {
		return false
	}
	for i := range this.GraphOutputNodeInfo {
		if !this.GraphOutputNodeInfo[i].Equal(that1.GraphOutputNodeInfo[i]) {
			return false
		}
	}
	if this.Destination != that1.Destination {
		return false
	}
	return true
}
func (this *GraphTransferNodeInput) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&framework.GraphTransferNodeInput{")
	s = append(s, "NodeId: "+fmt.Sprintf("%#v", this.NodeId)+",\n")
	s = append(s, "OutputPort: "+fmt.Sprintf("%#v", this.OutputPort)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphTransferNodeInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&framework.GraphTransferNodeInfo{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "NodeId: "+fmt.Sprintf("%#v", this.NodeId)+",\n")
	s = append(s, "TypeName: "+fmt.Sprintf("%#v", this.TypeName)+",\n")
	s = append(s, "SocOpId: "+fmt.Sprintf("%#v", this.SocOpId)+",\n")
	s = append(s, "PaddingId: "+fmt.Sprintf("%#v", this.PaddingId)+",\n")
	s = append(s, "InputCount: "+fmt.Sprintf("%#v", this.InputCount)+",\n")
	s = append(s, "OutputCount: "+fmt.Sprintf("%#v", this.OutputCount)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphTransferConstNodeInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&framework.GraphTransferConstNodeInfo{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "NodeId: "+fmt.Sprintf("%#v", this.NodeId)+",\n")
	s = append(s, "Shape: "+fmt.Sprintf("%#v", this.Shape)+",\n")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	s = append(s, "Dtype: "+fmt.Sprintf("%#v", this.Dtype)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphTransferNodeInputInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&framework.GraphTransferNodeInputInfo{")
	s = append(s, "NodeId: "+fmt.Sprintf("%#v", this.NodeId)+",\n")
	if this.NodeInput != nil {
		s = append(s, "NodeInput: "+fmt.Sprintf("%#v", this.NodeInput)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphTransferNodeOutputInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&framework.GraphTransferNodeOutputInfo{")
	s = append(s, "NodeId: "+fmt.Sprintf("%#v", this.NodeId)+",\n")
	s = append(s, "MaxByteSize: "+fmt.Sprintf("%#v", this.MaxByteSize)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphTransferGraphInputNodeInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&framework.GraphTransferGraphInputNodeInfo{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Shape: "+fmt.Sprintf("%#v", this.Shape)+",\n")
	s = append(s, "Dtype: "+fmt.Sprintf("%#v", this.Dtype)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphTransferGraphOutputNodeInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&framework.GraphTransferGraphOutputNodeInfo{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Shape: "+fmt.Sprintf("%#v", this.Shape)+",\n")
	s = append(s, "Dtype: "+fmt.Sprintf("%#v", this.Dtype)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphTransferInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&framework.GraphTransferInfo{")
	if this.NodeInfo != nil {
		s = append(s, "NodeInfo: "+fmt.Sprintf("%#v", this.NodeInfo)+",\n")
	}
	if this.ConstNodeInfo != nil {
		s = append(s, "ConstNodeInfo: "+fmt.Sprintf("%#v", this.ConstNodeInfo)+",\n")
	}
	if this.NodeInputInfo != nil {
		s = append(s, "NodeInputInfo: "+fmt.Sprintf("%#v", this.NodeInputInfo)+",\n")
	}
	if this.NodeOutputInfo != nil {
		s = append(s, "NodeOutputInfo: "+fmt.Sprintf("%#v", this.NodeOutputInfo)+",\n")
	}
	if this.GraphInputNodeInfo != nil {
		s = append(s, "GraphInputNodeInfo: "+fmt.Sprintf("%#v", this.GraphInputNodeInfo)+",\n")
	}
	if this.GraphOutputNodeInfo != nil {
		s = append(s, "GraphOutputNodeInfo: "+fmt.Sprintf("%#v", this.GraphOutputNodeInfo)+",\n")
	}
	s = append(s, "Destination: "+fmt.Sprintf("%#v", this.Destination)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringGraphTransferInfo(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *GraphTransferNodeInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphTransferNodeInput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.NodeId))
	}
	if m.OutputPort != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.OutputPort))
	}
	return i, nil
}

func (m *GraphTransferNodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphTransferNodeInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.NodeId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.NodeId))
	}
	if len(m.TypeName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(len(m.TypeName)))
		i += copy(dAtA[i:], m.TypeName)
	}
	if m.SocOpId != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.SocOpId))
	}
	if m.PaddingId != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.PaddingId))
	}
	if m.InputCount != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.InputCount))
	}
	if m.OutputCount != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.OutputCount))
	}
	return i, nil
}

func (m *GraphTransferConstNodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphTransferConstNodeInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.NodeId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.NodeId))
	}
	if len(m.Shape) > 0 {
		dAtA2 := make([]byte, len(m.Shape)*10)
		var j1 int
		for _, num1 := range m.Shape {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if m.Dtype != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.Dtype))
	}
	return i, nil
}

func (m *GraphTransferNodeInputInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphTransferNodeInputInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.NodeId))
	}
	if len(m.NodeInput) > 0 {
		for _, msg := range m.NodeInput {
			dAtA[i] = 0x12
			i++
			i = encodeVarintGraphTransferInfo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *GraphTransferNodeOutputInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphTransferNodeOutputInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.NodeId))
	}
	if len(m.MaxByteSize) > 0 {
		dAtA4 := make([]byte, len(m.MaxByteSize)*10)
		var j3 int
		for _, num1 := range m.MaxByteSize {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	return i, nil
}

func (m *GraphTransferGraphInputNodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphTransferGraphInputNodeInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Shape) > 0 {
		dAtA6 := make([]byte, len(m.Shape)*10)
		var j5 int
		for _, num1 := range m.Shape {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(j5))
		i += copy(dAtA[i:], dAtA6[:j5])
	}
	if m.Dtype != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.Dtype))
	}
	return i, nil
}

func (m *GraphTransferGraphOutputNodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphTransferGraphOutputNodeInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Shape) > 0 {
		dAtA8 := make([]byte, len(m.Shape)*10)
		var j7 int
		for _, num1 := range m.Shape {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(j7))
		i += copy(dAtA[i:], dAtA8[:j7])
	}
	if m.Dtype != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.Dtype))
	}
	return i, nil
}

func (m *GraphTransferInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphTransferInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.NodeInfo) > 0 {
		for _, msg := range m.NodeInfo {
			dAtA[i] = 0xa
			i++
			i = encodeVarintGraphTransferInfo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ConstNodeInfo) > 0 {
		for _, msg := range m.ConstNodeInfo {
			dAtA[i] = 0x12
			i++
			i = encodeVarintGraphTransferInfo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.NodeInputInfo) > 0 {
		for _, msg := range m.NodeInputInfo {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintGraphTransferInfo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.NodeOutputInfo) > 0 {
		for _, msg := range m.NodeOutputInfo {
			dAtA[i] = 0x22
			i++
			i = encodeVarintGraphTransferInfo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.GraphInputNodeInfo) > 0 {
		for _, msg := range m.GraphInputNodeInfo {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintGraphTransferInfo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.GraphOutputNodeInfo) > 0 {
		for _, msg := range m.GraphOutputNodeInfo {
			dAtA[i] = 0x32
			i++
			i = encodeVarintGraphTransferInfo(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Destination != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintGraphTransferInfo(dAtA, i, uint64(m.Destination))
	}
	return i, nil
}

func encodeVarintGraphTransferInfo(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *GraphTransferNodeInput) Size() (n int) {
	var l int
	_ = l
	if m.NodeId != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.NodeId))
	}
	if m.OutputPort != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.OutputPort))
	}
	return n
}

func (m *GraphTransferNodeInfo) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGraphTransferInfo(uint64(l))
	}
	if m.NodeId != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.NodeId))
	}
	l = len(m.TypeName)
	if l > 0 {
		n += 1 + l + sovGraphTransferInfo(uint64(l))
	}
	if m.SocOpId != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.SocOpId))
	}
	if m.PaddingId != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.PaddingId))
	}
	if m.InputCount != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.InputCount))
	}
	if m.OutputCount != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.OutputCount))
	}
	return n
}

func (m *GraphTransferConstNodeInfo) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGraphTransferInfo(uint64(l))
	}
	if m.NodeId != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.NodeId))
	}
	if len(m.Shape) > 0 {
		l = 0
		for _, e := range m.Shape {
			l += sovGraphTransferInfo(uint64(e))
		}
		n += 1 + sovGraphTransferInfo(uint64(l)) + l
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovGraphTransferInfo(uint64(l))
	}
	if m.Dtype != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.Dtype))
	}
	return n
}

func (m *GraphTransferNodeInputInfo) Size() (n int) {
	var l int
	_ = l
	if m.NodeId != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.NodeId))
	}
	if len(m.NodeInput) > 0 {
		for _, e := range m.NodeInput {
			l = e.Size()
			n += 1 + l + sovGraphTransferInfo(uint64(l))
		}
	}
	return n
}

func (m *GraphTransferNodeOutputInfo) Size() (n int) {
	var l int
	_ = l
	if m.NodeId != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.NodeId))
	}
	if len(m.MaxByteSize) > 0 {
		l = 0
		for _, e := range m.MaxByteSize {
			l += sovGraphTransferInfo(uint64(e))
		}
		n += 1 + sovGraphTransferInfo(uint64(l)) + l
	}
	return n
}

func (m *GraphTransferGraphInputNodeInfo) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGraphTransferInfo(uint64(l))
	}
	if len(m.Shape) > 0 {
		l = 0
		for _, e := range m.Shape {
			l += sovGraphTransferInfo(uint64(e))
		}
		n += 1 + sovGraphTransferInfo(uint64(l)) + l
	}
	if m.Dtype != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.Dtype))
	}
	return n
}

func (m *GraphTransferGraphOutputNodeInfo) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGraphTransferInfo(uint64(l))
	}
	if len(m.Shape) > 0 {
		l = 0
		for _, e := range m.Shape {
			l += sovGraphTransferInfo(uint64(e))
		}
		n += 1 + sovGraphTransferInfo(uint64(l)) + l
	}
	if m.Dtype != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.Dtype))
	}
	return n
}

func (m *GraphTransferInfo) Size() (n int) {
	var l int
	_ = l
	if len(m.NodeInfo) > 0 {
		for _, e := range m.NodeInfo {
			l = e.Size()
			n += 1 + l + sovGraphTransferInfo(uint64(l))
		}
	}
	if len(m.ConstNodeInfo) > 0 {
		for _, e := range m.ConstNodeInfo {
			l = e.Size()
			n += 1 + l + sovGraphTransferInfo(uint64(l))
		}
	}
	if len(m.NodeInputInfo) > 0 {
		for _, e := range m.NodeInputInfo {
			l = e.Size()
			n += 1 + l + sovGraphTransferInfo(uint64(l))
		}
	}
	if len(m.NodeOutputInfo) > 0 {
		for _, e := range m.NodeOutputInfo {
			l = e.Size()
			n += 1 + l + sovGraphTransferInfo(uint64(l))
		}
	}
	if len(m.GraphInputNodeInfo) > 0 {
		for _, e := range m.GraphInputNodeInfo {
			l = e.Size()
			n += 1 + l + sovGraphTransferInfo(uint64(l))
		}
	}
	if len(m.GraphOutputNodeInfo) > 0 {
		for _, e := range m.GraphOutputNodeInfo {
			l = e.Size()
			n += 1 + l + sovGraphTransferInfo(uint64(l))
		}
	}
	if m.Destination != 0 {
		n += 1 + sovGraphTransferInfo(uint64(m.Destination))
	}
	return n
}

func sovGraphTransferInfo(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGraphTransferInfo(x uint64) (n int) {
	return sovGraphTransferInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *GraphTransferNodeInput) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphTransferNodeInput{`,
		`NodeId:` + fmt.Sprintf("%v", this.NodeId) + `,`,
		`OutputPort:` + fmt.Sprintf("%v", this.OutputPort) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphTransferNodeInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphTransferNodeInfo{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`NodeId:` + fmt.Sprintf("%v", this.NodeId) + `,`,
		`TypeName:` + fmt.Sprintf("%v", this.TypeName) + `,`,
		`SocOpId:` + fmt.Sprintf("%v", this.SocOpId) + `,`,
		`PaddingId:` + fmt.Sprintf("%v", this.PaddingId) + `,`,
		`InputCount:` + fmt.Sprintf("%v", this.InputCount) + `,`,
		`OutputCount:` + fmt.Sprintf("%v", this.OutputCount) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphTransferConstNodeInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphTransferConstNodeInfo{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`NodeId:` + fmt.Sprintf("%v", this.NodeId) + `,`,
		`Shape:` + fmt.Sprintf("%v", this.Shape) + `,`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`Dtype:` + fmt.Sprintf("%v", this.Dtype) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphTransferNodeInputInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphTransferNodeInputInfo{`,
		`NodeId:` + fmt.Sprintf("%v", this.NodeId) + `,`,
		`NodeInput:` + strings.Replace(fmt.Sprintf("%v", this.NodeInput), "GraphTransferNodeInput", "GraphTransferNodeInput", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphTransferNodeOutputInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphTransferNodeOutputInfo{`,
		`NodeId:` + fmt.Sprintf("%v", this.NodeId) + `,`,
		`MaxByteSize:` + fmt.Sprintf("%v", this.MaxByteSize) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphTransferGraphInputNodeInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphTransferGraphInputNodeInfo{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Shape:` + fmt.Sprintf("%v", this.Shape) + `,`,
		`Dtype:` + fmt.Sprintf("%v", this.Dtype) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphTransferGraphOutputNodeInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphTransferGraphOutputNodeInfo{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Shape:` + fmt.Sprintf("%v", this.Shape) + `,`,
		`Dtype:` + fmt.Sprintf("%v", this.Dtype) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphTransferInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphTransferInfo{`,
		`NodeInfo:` + strings.Replace(fmt.Sprintf("%v", this.NodeInfo), "GraphTransferNodeInfo", "GraphTransferNodeInfo", 1) + `,`,
		`ConstNodeInfo:` + strings.Replace(fmt.Sprintf("%v", this.ConstNodeInfo), "GraphTransferConstNodeInfo", "GraphTransferConstNodeInfo", 1) + `,`,
		`NodeInputInfo:` + strings.Replace(fmt.Sprintf("%v", this.NodeInputInfo), "GraphTransferNodeInputInfo", "GraphTransferNodeInputInfo", 1) + `,`,
		`NodeOutputInfo:` + strings.Replace(fmt.Sprintf("%v", this.NodeOutputInfo), "GraphTransferNodeOutputInfo", "GraphTransferNodeOutputInfo", 1) + `,`,
		`GraphInputNodeInfo:` + strings.Replace(fmt.Sprintf("%v", this.GraphInputNodeInfo), "GraphTransferGraphInputNodeInfo", "GraphTransferGraphInputNodeInfo", 1) + `,`,
		`GraphOutputNodeInfo:` + strings.Replace(fmt.Sprintf("%v", this.GraphOutputNodeInfo), "GraphTransferGraphOutputNodeInfo", "GraphTransferGraphOutputNodeInfo", 1) + `,`,
		`Destination:` + fmt.Sprintf("%v", this.Destination) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGraphTransferInfo(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *GraphTransferNodeInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphTransferNodeInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphTransferNodeInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputPort", wireType)
			}
			m.OutputPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutputPort |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraphTransferInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphTransferNodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphTransferNodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphTransferNodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TypeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SocOpId", wireType)
			}
			m.SocOpId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SocOpId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaddingId", wireType)
			}
			m.PaddingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaddingId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputCount", wireType)
			}
			m.InputCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InputCount |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputCount", wireType)
			}
			m.OutputCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutputCount |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraphTransferInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphTransferConstNodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphTransferConstNodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphTransferConstNodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Shape = append(m.Shape, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraphTransferInfo
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraphTransferInfo
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Shape = append(m.Shape, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Shape", wireType)
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dtype", wireType)
			}
			m.Dtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Dtype |= (DataType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraphTransferInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphTransferNodeInputInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphTransferNodeInputInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphTransferNodeInputInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeInput", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeInput = append(m.NodeInput, &GraphTransferNodeInput{})
			if err := m.NodeInput[len(m.NodeInput)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGraphTransferInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphTransferNodeOutputInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphTransferNodeOutputInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphTransferNodeOutputInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			m.NodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.MaxByteSize = append(m.MaxByteSize, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraphTransferInfo
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraphTransferInfo
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.MaxByteSize = append(m.MaxByteSize, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxByteSize", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraphTransferInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphTransferGraphInputNodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphTransferGraphInputNodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphTransferGraphInputNodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Shape = append(m.Shape, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraphTransferInfo
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraphTransferInfo
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Shape = append(m.Shape, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Shape", wireType)
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dtype", wireType)
			}
			m.Dtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Dtype |= (DataType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraphTransferInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphTransferGraphOutputNodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphTransferGraphOutputNodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphTransferGraphOutputNodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (int64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Shape = append(m.Shape, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraphTransferInfo
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraphTransferInfo
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Shape = append(m.Shape, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Shape", wireType)
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dtype", wireType)
			}
			m.Dtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Dtype |= (DataType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraphTransferInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphTransferInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphTransferInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphTransferInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeInfo = append(m.NodeInfo, &GraphTransferNodeInfo{})
			if err := m.NodeInfo[len(m.NodeInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConstNodeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConstNodeInfo = append(m.ConstNodeInfo, &GraphTransferConstNodeInfo{})
			if err := m.ConstNodeInfo[len(m.ConstNodeInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeInputInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeInputInfo = append(m.NodeInputInfo, &GraphTransferNodeInputInfo{})
			if err := m.NodeInputInfo[len(m.NodeInputInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeOutputInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeOutputInfo = append(m.NodeOutputInfo, &GraphTransferNodeOutputInfo{})
			if err := m.NodeOutputInfo[len(m.NodeOutputInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphInputNodeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GraphInputNodeInfo = append(m.GraphInputNodeInfo, &GraphTransferGraphInputNodeInfo{})
			if err := m.GraphInputNodeInfo[len(m.GraphInputNodeInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphOutputNodeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GraphOutputNodeInfo = append(m.GraphOutputNodeInfo, &GraphTransferGraphOutputNodeInfo{})
			if err := m.GraphOutputNodeInfo[len(m.GraphOutputNodeInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			m.Destination = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Destination |= (GraphTransferInfo_Destination(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraphTransferInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGraphTransferInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGraphTransferInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGraphTransferInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGraphTransferInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGraphTransferInfo
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGraphTransferInfo
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGraphTransferInfo(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGraphTransferInfo = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGraphTransferInfo   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("tensorflow/core/framework/graph_transfer_info.proto", fileDescriptorGraphTransferInfo)
}

var fileDescriptorGraphTransferInfo = []byte{
	// 725 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xcd, 0xe4, 0xd9, 0xdc, 0xf4, 0x85, 0x69, 0x4b, 0xd4, 0x0a, 0xb7, 0x35, 0x02, 0xca, 0x43,
	0x89, 0xd4, 0xae, 0x41, 0xea, 0x03, 0x95, 0x0a, 0x29, 0x09, 0x43, 0x17, 0xa8, 0x0b, 0xac, 0x69,
	0x3c, 0x49, 0x2d, 0xc8, 0x8c, 0x65, 0x4f, 0xd4, 0xa6, 0x2b, 0x3e, 0x81, 0x3f, 0x40, 0x62, 0xc5,
	0xa7, 0xb0, 0xec, 0x92, 0x65, 0x1b, 0x36, 0x2c, 0xbb, 0x44, 0x62, 0x83, 0x66, 0x26, 0x8d, 0xed,
	0xe6, 0x51, 0x84, 0xc4, 0x6e, 0x1e, 0xf7, 0x9e, 0x73, 0xcf, 0xbd, 0xc7, 0x1e, 0xd8, 0x10, 0x94,
	0x05, 0xdc, 0x6f, 0x7c, 0xe0, 0xc7, 0xe5, 0x3a, 0xf7, 0x69, 0xb9, 0xe1, 0x93, 0x16, 0x3d, 0xe6,
	0xfe, 0xfb, 0x72, 0xd3, 0x27, 0xde, 0x91, 0x2d, 0x7c, 0xc2, 0x82, 0x06, 0xf5, 0x6d, 0x97, 0x35,
	0x78, 0xc9, 0xf3, 0xb9, 0xe0, 0x06, 0x84, 0x49, 0x8b, 0xf7, 0x47, 0x03, 0x88, 0x8e, 0x47, 0x03,
	0x9d, 0x62, 0x61, 0x58, 0xd8, 0x95, 0x78, 0xfb, 0x3d, 0xb8, 0x0a, 0x77, 0xe8, 0x1e, 0xf3, 0xda,
	0xc2, 0xb8, 0x03, 0x39, 0xc6, 0x1d, 0x6a, 0xbb, 0x4e, 0x11, 0xad, 0xa0, 0xb5, 0x0c, 0xce, 0xca,
	0xed, 0x9e, 0x63, 0x2c, 0x43, 0x81, 0xb7, 0x85, 0xd7, 0x16, 0xb6, 0xc7, 0x7d, 0x51, 0x4c, 0xaa,
	0x4b, 0xd0, 0x47, 0x35, 0xee, 0x0b, 0xeb, 0x1c, 0xc1, 0xfc, 0x10, 0xd0, 0x06, 0x37, 0x0c, 0x48,
	0x33, 0xd2, 0xa2, 0x0a, 0x30, 0x8f, 0xd5, 0x3a, 0xca, 0x93, 0x8c, 0xf1, 0x2c, 0x41, 0x5e, 0x56,
	0x6a, 0xab, 0x8c, 0x94, 0xca, 0x98, 0x90, 0x07, 0x15, 0x99, 0xb5, 0x08, 0xf9, 0x80, 0xd7, 0x6d,
	0xee, 0xc9, 0xbc, 0xb4, 0xca, 0xcb, 0x05, 0xbc, 0x5e, 0xf5, 0xf6, 0x1c, 0xe3, 0x2e, 0x80, 0x47,
	0x1c, 0xc7, 0x65, 0x4d, 0x79, 0x99, 0x51, 0x97, 0xf9, 0xde, 0x89, 0xae, 0xdf, 0x95, 0x0a, 0xed,
	0x3a, 0x6f, 0x33, 0x51, 0xcc, 0xea, 0xfa, 0xd5, 0xd1, 0xb6, 0x3c, 0x31, 0x56, 0x61, 0xb2, 0x27,
	0x50, 0x47, 0xe4, 0x54, 0x44, 0x4f, 0xb4, 0x0a, 0xb1, 0x3e, 0x23, 0x58, 0x8c, 0x49, 0xdc, 0xe6,
	0x2c, 0x10, 0xff, 0xa6, 0x73, 0x0e, 0x32, 0xc1, 0x11, 0xf1, 0xa4, 0xc6, 0xd4, 0x5a, 0x0a, 0xeb,
	0x8d, 0x84, 0x70, 0x88, 0x20, 0x4a, 0xdb, 0x24, 0x56, 0x6b, 0xe3, 0x31, 0x64, 0x1c, 0xd9, 0x01,
	0xa5, 0x69, 0x7a, 0x7d, 0xae, 0x14, 0xce, 0xb8, 0xb4, 0x43, 0x04, 0xd9, 0xef, 0x78, 0x14, 0xeb,
	0x10, 0xeb, 0xe4, 0x5a, 0x81, 0xfd, 0xc1, 0xaa, 0x02, 0x47, 0x0e, 0x77, 0x13, 0x40, 0x5f, 0xc8,
	0xd0, 0x62, 0x72, 0x25, 0xb5, 0x56, 0x58, 0xb7, 0xa2, 0x3c, 0xc3, 0x41, 0x71, 0x9e, 0x5d, 0x2d,
	0xad, 0x03, 0x58, 0x1a, 0x08, 0xaa, 0xaa, 0xde, 0x8d, 0xa7, 0xb6, 0x60, 0xaa, 0x45, 0x4e, 0xec,
	0xc3, 0x8e, 0xa0, 0x76, 0xe0, 0x9e, 0x52, 0xc5, 0x9e, 0xc1, 0x85, 0x16, 0x39, 0xd9, 0xea, 0x08,
	0xfa, 0xc6, 0x3d, 0xa5, 0xd6, 0x31, 0x2c, 0xc7, 0xb0, 0xd5, 0x46, 0xd1, 0x8e, 0xed, 0x7d, 0xbf,
	0xc5, 0xc9, 0x68, 0x8b, 0xfb, 0xed, 0x4c, 0xfd, 0x4d, 0x3b, 0x57, 0x06, 0x89, 0xb5, 0xaa, 0xff,
	0xcc, 0xfc, 0x3b, 0x0d, 0xb7, 0x62, 0xd4, 0x8a, 0xeb, 0x39, 0xe4, 0x7b, 0x73, 0x6a, 0xf0, 0x22,
	0x52, 0x63, 0x5a, 0xbd, 0x61, 0x4c, 0x0d, 0x8e, 0x27, 0xd8, 0x55, 0xad, 0x15, 0x98, 0xa9, 0x4b,
	0xcb, 0xda, 0x21, 0x8a, 0x1e, 0xf6, 0x83, 0x91, 0x28, 0x31, 0x8b, 0xe3, 0xa9, 0x7a, 0xcc, 0xf1,
	0x15, 0x98, 0x09, 0x7d, 0xa3, 0xf1, 0x52, 0x37, 0xe0, 0xc5, 0x1c, 0x89, 0xa7, 0x58, 0xcc, 0xa0,
	0xaf, 0x61, 0x56, 0xe1, 0xf5, 0x3e, 0x44, 0x05, 0x98, 0x56, 0x80, 0x0f, 0xc7, 0x02, 0x86, 0x46,
	0xc3, 0xd3, 0x2c, 0x6e, 0xbc, 0x77, 0x30, 0xaf, 0x7f, 0x9d, 0xba, 0xc6, 0x50, 0x78, 0x46, 0xe1,
	0x3e, 0x19, 0x89, 0x3b, 0x68, 0x32, 0x6c, 0x34, 0x07, 0x8d, 0x47, 0x60, 0x41, 0xe3, 0xf7, 0x6a,
	0x0e, 0x09, 0xb2, 0x8a, 0xe0, 0xe9, 0x78, 0x82, 0xb8, 0x99, 0xf0, 0xed, 0xe6, 0x10, 0x87, 0xbd,
	0x82, 0x82, 0x43, 0x03, 0xe1, 0x32, 0x22, 0x5c, 0xce, 0xd4, 0x8f, 0x69, 0x7a, 0xfd, 0xd1, 0x48,
	0x5c, 0x99, 0x53, 0xda, 0x09, 0x13, 0x70, 0x34, 0xdb, 0xba, 0x07, 0x85, 0xc8, 0x9d, 0x91, 0x83,
	0x54, 0xa5, 0x5a, 0x9b, 0x4d, 0x18, 0x05, 0xc8, 0xbd, 0x7c, 0xf1, 0x76, 0x73, 0xb7, 0x5a, 0x99,
	0x45, 0x5b, 0x5f, 0xd0, 0xd9, 0x85, 0x99, 0xf8, 0x7e, 0x61, 0x26, 0x2e, 0x2f, 0x4c, 0xf4, 0xb1,
	0x6b, 0xa2, 0xaf, 0x5d, 0x13, 0x7d, 0xeb, 0x9a, 0xe8, 0xac, 0x6b, 0xa2, 0xf3, 0xae, 0x89, 0x7e,
	0x76, 0xcd, 0xc4, 0x65, 0xd7, 0x44, 0x9f, 0x7e, 0x98, 0x09, 0x28, 0x72, 0xbf, 0x19, 0x2d, 0xa7,
	0xff, 0xe8, 0x6c, 0x2d, 0x0c, 0x54, 0x56, 0x93, 0x0f, 0x50, 0x0d, 0x1d, 0x3c, 0x6b, 0xba, 0xe2,
	0xa8, 0x7d, 0x58, 0xaa, 0xf3, 0x56, 0x39, 0xf2, 0x68, 0x0d, 0x5f, 0x36, 0xf9, 0xb5, 0xd7, 0xec,
	0x17, 0x42, 0x87, 0x59, 0xf5, 0x96, 0x6d, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x19, 0x78,
	0x05, 0x35, 0x07, 0x00, 0x00,
}
