// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tensorflow/core/framework/reader_base.proto

package framework

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// For serializing and restoring the state of ReaderBase, see
// reader_base.h for details.
type ReaderBaseState struct {
	WorkStarted        int64  `protobuf:"varint,1,opt,name=work_started,json=workStarted,proto3" json:"work_started,omitempty"`
	WorkFinished       int64  `protobuf:"varint,2,opt,name=work_finished,json=workFinished,proto3" json:"work_finished,omitempty"`
	NumRecordsProduced int64  `protobuf:"varint,3,opt,name=num_records_produced,json=numRecordsProduced,proto3" json:"num_records_produced,omitempty"`
	CurrentWork        []byte `protobuf:"bytes,4,opt,name=current_work,json=currentWork,proto3" json:"current_work,omitempty"`
}

func (m *ReaderBaseState) Reset()                    { *m = ReaderBaseState{} }
func (*ReaderBaseState) ProtoMessage()               {}
func (*ReaderBaseState) Descriptor() ([]byte, []int) { return fileDescriptorReaderBase, []int{0} }

func (m *ReaderBaseState) GetWorkStarted() int64 {
	if m != nil {
		return m.WorkStarted
	}
	return 0
}

func (m *ReaderBaseState) GetWorkFinished() int64 {
	if m != nil {
		return m.WorkFinished
	}
	return 0
}

func (m *ReaderBaseState) GetNumRecordsProduced() int64 {
	if m != nil {
		return m.NumRecordsProduced
	}
	return 0
}

func (m *ReaderBaseState) GetCurrentWork() []byte {
	if m != nil {
		return m.CurrentWork
	}
	return nil
}

func init() {
	proto.RegisterType((*ReaderBaseState)(nil), "tensorflow.ReaderBaseState")
}
func (this *ReaderBaseState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReaderBaseState)
	if !ok {
		that2, ok := that.(ReaderBaseState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.WorkStarted != that1.WorkStarted {
		return false
	}
	if this.WorkFinished != that1.WorkFinished {
		return false
	}
	if this.NumRecordsProduced != that1.NumRecordsProduced {
		return false
	}
	if !bytes.Equal(this.CurrentWork, that1.CurrentWork) {
		return false
	}
	return true
}
func (this *ReaderBaseState) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&framework.ReaderBaseState{")
	s = append(s, "WorkStarted: "+fmt.Sprintf("%#v", this.WorkStarted)+",\n")
	s = append(s, "WorkFinished: "+fmt.Sprintf("%#v", this.WorkFinished)+",\n")
	s = append(s, "NumRecordsProduced: "+fmt.Sprintf("%#v", this.NumRecordsProduced)+",\n")
	s = append(s, "CurrentWork: "+fmt.Sprintf("%#v", this.CurrentWork)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringReaderBase(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *ReaderBaseState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReaderBaseState) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.WorkStarted != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintReaderBase(dAtA, i, uint64(m.WorkStarted))
	}
	if m.WorkFinished != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintReaderBase(dAtA, i, uint64(m.WorkFinished))
	}
	if m.NumRecordsProduced != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintReaderBase(dAtA, i, uint64(m.NumRecordsProduced))
	}
	if len(m.CurrentWork) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintReaderBase(dAtA, i, uint64(len(m.CurrentWork)))
		i += copy(dAtA[i:], m.CurrentWork)
	}
	return i, nil
}

func encodeVarintReaderBase(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ReaderBaseState) Size() (n int) {
	var l int
	_ = l
	if m.WorkStarted != 0 {
		n += 1 + sovReaderBase(uint64(m.WorkStarted))
	}
	if m.WorkFinished != 0 {
		n += 1 + sovReaderBase(uint64(m.WorkFinished))
	}
	if m.NumRecordsProduced != 0 {
		n += 1 + sovReaderBase(uint64(m.NumRecordsProduced))
	}
	l = len(m.CurrentWork)
	if l > 0 {
		n += 1 + l + sovReaderBase(uint64(l))
	}
	return n
}

func sovReaderBase(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozReaderBase(x uint64) (n int) {
	return sovReaderBase(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ReaderBaseState) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ReaderBaseState{`,
		`WorkStarted:` + fmt.Sprintf("%v", this.WorkStarted) + `,`,
		`WorkFinished:` + fmt.Sprintf("%v", this.WorkFinished) + `,`,
		`NumRecordsProduced:` + fmt.Sprintf("%v", this.NumRecordsProduced) + `,`,
		`CurrentWork:` + fmt.Sprintf("%v", this.CurrentWork) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringReaderBase(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ReaderBaseState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReaderBase
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReaderBaseState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReaderBaseState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkStarted", wireType)
			}
			m.WorkStarted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReaderBase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkStarted |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkFinished", wireType)
			}
			m.WorkFinished = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReaderBase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkFinished |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumRecordsProduced", wireType)
			}
			m.NumRecordsProduced = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReaderBase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumRecordsProduced |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentWork", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReaderBase
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthReaderBase
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentWork = append(m.CurrentWork[:0], dAtA[iNdEx:postIndex]...)
			if m.CurrentWork == nil {
				m.CurrentWork = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReaderBase(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthReaderBase
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReaderBase(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReaderBase
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReaderBase
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReaderBase
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthReaderBase
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowReaderBase
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipReaderBase(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthReaderBase = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReaderBase   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("tensorflow/core/framework/reader_base.proto", fileDescriptorReaderBase)
}

var fileDescriptorReaderBase = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4a, 0x03, 0x41,
	0x10, 0xc6, 0x6f, 0x8c, 0x58, 0x6c, 0x22, 0xca, 0x61, 0x71, 0xd5, 0x12, 0xb5, 0x09, 0x08, 0x77,
	0x82, 0xb5, 0x4d, 0x0a, 0xeb, 0x70, 0x29, 0x04, 0x9b, 0x63, 0x73, 0x3b, 0xf9, 0x43, 0xbc, 0x9b,
	0x30, 0xbb, 0x47, 0x5a, 0x1f, 0xc1, 0x07, 0xf0, 0x01, 0xac, 0x7c, 0x0e, 0xcb, 0x94, 0x96, 0x66,
	0x6d, 0x2c, 0x53, 0x5a, 0xca, 0x6d, 0x82, 0x27, 0x62, 0xb7, 0x7c, 0xf3, 0x9b, 0x1d, 0xbe, 0x9f,
	0xb8, 0xb0, 0x58, 0x1a, 0xe2, 0xf1, 0x3d, 0x2d, 0x93, 0x9c, 0x18, 0x93, 0x31, 0xab, 0x02, 0x97,
	0xc4, 0xf3, 0x84, 0x51, 0x69, 0xe4, 0x6c, 0xa4, 0x0c, 0xc6, 0x0b, 0x26, 0x4b, 0xa1, 0x68, 0xe0,
	0xb3, 0x17, 0x10, 0x47, 0xa9, 0x27, 0xfa, 0xca, 0xe0, 0xd0, 0x2a, 0x8b, 0xe1, 0xa9, 0xe8, 0xd4,
	0x9b, 0x99, 0xb1, 0x8a, 0x2d, 0xea, 0x08, 0xba, 0xd0, 0x6b, 0xa5, 0xed, 0x3a, 0x1b, 0x6e, 0xa3,
	0xf0, 0x5c, 0x1c, 0x7a, 0x64, 0x3c, 0x2b, 0x67, 0x66, 0x8a, 0x3a, 0xda, 0xf3, 0x8c, 0xdf, 0xbb,
	0xd9, 0x65, 0xe1, 0xa5, 0x38, 0x29, 0xab, 0x22, 0x63, 0xcc, 0x89, 0xb5, 0xc9, 0x16, 0x4c, 0xba,
	0xca, 0x51, 0x47, 0x2d, 0xcf, 0x86, 0x65, 0x55, 0xa4, 0xdb, 0xd1, 0x60, 0x37, 0xa9, 0x2f, 0xe7,
	0x15, 0x33, 0x96, 0x36, 0xab, 0x7f, 0x8a, 0xf6, 0xbb, 0xd0, 0xeb, 0xa4, 0xed, 0x5d, 0x76, 0x4b,
	0x3c, 0xef, 0x3f, 0xc1, 0x6a, 0x2d, 0x83, 0xb7, 0xb5, 0x0c, 0x36, 0x6b, 0x09, 0x0f, 0x4e, 0xc2,
	0xb3, 0x93, 0xf0, 0xea, 0x24, 0xac, 0x9c, 0x84, 0x77, 0x27, 0xe1, 0xd3, 0xc9, 0x60, 0xe3, 0x24,
	0x3c, 0x7e, 0xc8, 0x40, 0x44, 0xc4, 0x93, 0xb8, 0xe9, 0x1b, 0xff, 0x78, 0xe9, 0x1f, 0x37, 0xb5,
	0x07, 0xb5, 0x16, 0x33, 0x80, 0xbb, 0xeb, 0xc9, 0xcc, 0x4e, 0xab, 0x51, 0x9c, 0x53, 0x91, 0xfc,
	0x32, 0xfa, 0xff, 0x73, 0x42, 0x7f, 0x54, 0x7f, 0x01, 0x8c, 0x0e, 0xbc, 0xe2, 0xab, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0xab, 0x4a, 0x55, 0x91, 0x01, 0x00, 0x00,
}
